schemaVersion: 1
enabledWorkflows:
  - project-discovery
  - device
  - simulator
  - xcode-ide
sessionDefaults:
  projectPath: ./LoopLooper/LoopLooper.xcodeproj
  scheme: LoopLooper
  configuration: Debug
  preferXcodebuild: true
  platform: tvOS
  bundleId: com.lex.LoopLooper
  deviceId: F471BF1B-BE14-5770-86A5-6194ADAE7E00
